version: "3"
services:
  mongo:
    image: "mongo:4.2.16-bionic"
    container_name: database
    environment:
      MONGO_INIT_DATABASE: db
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "1234"
    ports:
      - 27017:2017
